### ISSUE TITLE
Would compiz-reloaded work with pantheon-3d

### ISSUE THREAD

**Issue by SolarAquarion** [quequotion/pantheon-bzr-qq#3]

**Comment by quequotion** [comment]
In theory, yes. I have not tried it, but there's nothing in the 0.9.x branch that is _required_ for the rest of the desktop to function. compiz-core does not have "compiz" in provides(), so you'd need to customize the PKGBUILD to depend on compiz-core rather than compiz.

**Comment by quequotion** [comment]
Sounds like this will have to happen sooner or later. I don't expect Canonical to continue maintaining compiz after they discontinue Unity.

**Comment by quequotion** [comment]
I recently had the opportunity to try this out.

It definetly does work, but you'll need to change the PKGBUILD to depend on compiz-core instead of compiz, on line 13.

https://github.com/quequotion/pantheon-bzr-qq/blob/d116d91721c8efee32f5ba4cc3dac7159c978dc0/pantheon-3d/PKGBUILD#L13
