### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [quequotion/pantheon-bzr-qq#5]
-> Remove Gala dependecies
patching file src/PanelWindow.vala
Hunk #1 succeeded at 122 with fuzz 2 (offset 36 lines).
Hunk #2 succeeded at 263 with fuzz 2 (offset 112 lines).
Hunk #3 succeeded at 273 (offset 112 lines).
patching file src/Widgets/Panel.vala
Hunk #2 FAILED at 63.
Hunk #3 succeeded at 266 (offset 4 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/Widgets/Panel.vala.rej
patching file src/CMakeLists.txt

**Comment by quequotion** [comment]
Was this ever addressed? Looks like you had trouble building wingpanel.

Was it wingpanel-stanadlone-git? As far as I know, this package is working.

It was last year; it must have been an earlier package.
