### ISSUE TITLE
It would be interesting if you can forward port the gnome-setting-daemon patches to 3.34

### ISSUE THREAD

**Issue by SolarAquarion** [quequotion/pantheon-bzr-qq#6]
But if you can't no harm done

**Comment by SolarAquarion** [comment]
@quequotion wingpanel-standalone patch is failing

**Comment by quequotion** [comment]
Sorry I haven't gotten around to this yet; hopefully I can make time soon.

**Comment by quequotion** [comment]
@SolarAquarion Sorry I haven't gotten around to this yet, hopefully I can make time soon.

**Comment by quequotion** [comment]
@SolarAquarion although I wasn't able to reproduce the bug with the latest version of wingpanel, it came up while I built some previous commits to isolate [this bug](https://github.com/elementary/wingpanel/pull/295#issuecomment-644239633) and it is now fixed.

By the way, this isn't really the place to talk about wingpanel-standalone-git (I get emails for the discussions on the AUR page anyway) and I'm probably going to abandon gnome-settings-daemon-elementary (gnome-settings-daemon is no longer useful for Pantheon-3D; I've had to replace it with cinnamon-settings-daemon), so I will close this issue.
