### ISSUE TITLE
Not a git url

### ISSUE THREAD

**Issue by SolarAquarion** [quequotion/pantheon-bzr-qq#7]
https://github.com/quequotion/pantheon-qq/blob/f0db4cccceaf18ae91b3bf0b30ba8d61fd19f4c4/pantheon-dock-instctl-git/PKGBUILD#L9

**Comment by quequotion** [comment]
This is a link to a reddit post with a video demonstrating the "instance controls" patch.

I have not yet made a pull request against Dock on github to be linked. The only other place to link would be the [merge request](https://code.launchpad.net/~quequotion/plank/+git/plank/+merge/390649) against Plank on launchpad. 

This is not a link to get more info bout Dock, it is a link to get more info about my patch.

**Comment by SolarAquarion** [comment]
But the git leads to the url

**Comment by quequotion** [comment]
omg! I just realized what you are talking about

I need to fix line 16

`source=(pantheon-dock::git+$url`

The original PKGBUILD could use $url there because the "info" and source link were the same. I must have made that change *after* building it locally. Oops.

**Comment by quequotion** [comment]
fixed in commit ac9eefc28507fd90f653e48edabc4edf83bb6457
